repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(js|jsx|md)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        entry: codespell --ignore-words=.codespell_ignore --quiet-level=4 --check-filenames
        exclude: \.(csv|json|txt)$
